// export { 
//     fetchSoedirmanLoadValue,
//     fetchSoedirmanLoadSecondValue,
//     fetchSoedirmanLoadThirdValue,
//     fetchSoedirmanWaterLevel,
//     fetchGunungWugulLoadValue,
//     fetchGunungWugulLoadSecondValue,
//     fetchGunungWugulWaterLevel,
//     fetchTapenLoadValue,
//     fetchTapenWaterLevel,
//     fetchKedungomboLoadValue,
//     fetchKedungomboWaterLevel,
//     fetchKlambuLoadValue,
//     fetchKlambuWaterLevelAo,
//     fetchSidorejoLoadValue,
//     fetchSidorejoWaterLevel,
//     fetchKetengerLoadValue,
//     fetchKetengerLoadSecondValue,
//     fetchKetengerLoadThirdValue,
//     fetchKetengerLoadFourthValue
//   } from ';